package GUI.GestionInformacion.Empleado;


import Control.ControlEmpleado;
import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Excepciones.MiExcepcion;
import Modelo.Validadores.LanzarMensaje;
import Modelo.Validadores.Validador;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * JIFCrearEmpleado 21/12/2015
 *
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 */
public class JIFCrearEmpleado extends AnclarVentanaInterna {

    /**
     * Creates new form JIFEmployee
     *
     * @param title Un string correspondiente al titulo del JInternalFrame
     * @param parent_w
     * @param parent_h
     */
    public JIFCrearEmpleado(String title, int parent_w, int parent_h) {
        super();
        setTitle(title);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(900, 425);
        setLocation((int) (Math.abs(parent_w - getSize().width) / 2), (int) (Math.abs(parent_h - getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        // INICIALIZAMOS COMPONENTES
        initComponents();
        // INICIALIZAMOS ATRIBUTOS
        validador = new Validador();
        controlEmpleado = new ControlEmpleado();
        lanzarMensaje = new LanzarMensaje(this);
        
        // CONTROL
        
        // Definimos el valor de la acción por defecto siempre en -1.
        
        // ACTUALIZAMOS EL COMBOBOX Y SETEAMOS SU ActionListener
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPId = new javax.swing.JPanel();
        jLIdentification = new javax.swing.JLabel();
        jTFIdentification = new javax.swing.JTextField();
        jCBIdentification = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFcedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFnombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFapellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDCfecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jCBestado_civil = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTFsalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBcargo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTFtelefono = new javax.swing.JTextField();
        jPFormControl = new javax.swing.JPanel();
        jBcrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLIdentification.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLIdentification.setText("Identificación: ");
        jPId.add(jLIdentification);

        jTFIdentification = new javax.swing.JTextField(20);
        jPId.add(jTFIdentification);

        jPId.add(jCBIdentification);

        jLabel10.setText("Cargo");

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 800));

        jPForm.setLayout(new java.awt.GridLayout(8, 2, 5, 5));

        jLabel3.setText("Cedula ");
        jPForm.add(jLabel3);

        jTFcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcedulaActionPerformed(evt);
            }
        });
        jPForm.add(jTFcedula);

        jLabel4.setText("Nombres");
        jPForm.add(jLabel4);

        jTFnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombresActionPerformed(evt);
            }
        });
        jPForm.add(jTFnombres);

        jLabel8.setText("Apellidos");
        jPForm.add(jLabel8);

        jTFapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFapellidosActionPerformed(evt);
            }
        });
        jPForm.add(jTFapellidos);

        jLabel9.setText("Fecha de nacimiento");
        jPForm.add(jLabel9);

        jDCfecha_nacimiento.setDateFormatString("yyyy-MM-dd");
        jPForm.add(jDCfecha_nacimiento);

        jLabel2.setText("Estado civil");
        jPForm.add(jLabel2);

        jCBestado_civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el estado civil...", "SOLTERO(A)", "CASADO(A)", "VIUDO(A)", "UNION LIBRE", "DIVORCIADO(A)" }));
        jPForm.add(jCBestado_civil);

        jLabel5.setText("Salario");
        jPForm.add(jLabel5);
        jPForm.add(jTFsalario);

        jLabel6.setText("Cargo");
        jPForm.add(jLabel6);

        jCBcargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el cargo...", "DIRECTOR(A)", "CONDUCTOR(A)", "AUXILIAR" }));
        jPForm.add(jCBcargo);

        jLabel7.setText("Telefono");
        jPForm.add(jLabel7);

        jTFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtelefonoActionPerformed(evt);
            }
        });
        jPForm.add(jTFtelefono);

        getContentPane().add(jPForm, java.awt.BorderLayout.CENTER);

        jPFormControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBcrear.setText("CREAR");
        jBcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcrearActionPerformed(evt);
            }
        });
        jPFormControl.add(jBcrear);

        getContentPane().add(jPFormControl, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestion de Empleados");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cleanGeneralDataForm.
     */
    
    /**
     * searchContract [Método encargado de buscar un contrato y colocar su
     * información en el formulario].
     *
     * @throws MyException
     */
    
    
    public void limpiarCampos() {
       jTFcedula.setText("");
       jTFsalario.setText("");
       jTFnombres.setText("");
       jTFapellidos.setText("");
       jTFtelefono.setText("");
       ((JTextField) jDCfecha_nacimiento.getDateEditor()).setText("");
       jCBestado_civil.setSelectedIndex(0);
       jCBcargo.setSelectedIndex(0);
    }
    
    private void jBcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcrearActionPerformed
       String arregloEmpleado[] = new  String[8];     
       arregloEmpleado[0] = jTFcedula.getText();
       arregloEmpleado[1] = jTFsalario.getText().trim();
       arregloEmpleado[2] = jTFnombres.getText().toUpperCase().trim();
       arregloEmpleado[3] = jTFapellidos.getText().toUpperCase().trim();
       arregloEmpleado[4] = jTFtelefono.getText().trim();
       arregloEmpleado[5] = ((JTextField) jDCfecha_nacimiento.getDateEditor()).getText();
       arregloEmpleado[6] = (String) jCBestado_civil.getSelectedItem();
       arregloEmpleado[7] = (String) jCBcargo.getSelectedItem();
       
       boolean error = false;
        try {
                                   
            validador.validarCampoVacio(arregloEmpleado[0], "CÉDULA");  
            validador.validarCadenaNumeros(arregloEmpleado[0], "CÉDULA");
            validador.validarCampoVacio(arregloEmpleado[2], "NOMBRES");
            validador.validarCampoVacio(arregloEmpleado[3], "APELLIDOS");  
            validador.validarCampoVacio(arregloEmpleado[1], "SALARIO");              
            validador.validarDouble(arregloEmpleado[1], "SALARIO");
                        
            if(arregloEmpleado[5].equals("")) {
                arregloEmpleado[5] = null;
            }
            
            if(jCBcargo.getSelectedIndex()==0) {
                lanzarMensaje.mostrarMessageDialog("Debe seleccionar algún cargo para el empleado.", title, JOptionPane.INFORMATION_MESSAGE);
                error = true;
            }          
                        
            if(!arregloEmpleado[4].equals("")) {
                validador.validarNumeroTelefonico(arregloEmpleado[4]);
            }
            
            if(arregloEmpleado[6].equals(jCBestado_civil.getItemAt(0))){
                arregloEmpleado[6] = "";
            }
            
            if(!error) {
            controlEmpleado.crearEmpleado(arregloEmpleado);
            
            lanzarMensaje.mostrarMessageDialog("Se ha creado un registro para el empleado con éxito.", title, JOptionPane.INFORMATION_MESSAGE);
            
            limpiarCampos();
            }
        } catch (MiExcepcion ex) {
           lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jBcrearActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTFnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombresActionPerformed

    private void jTFapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFapellidosActionPerformed

    private void jTFcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcedulaActionPerformed

    private void jTFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtelefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBcrear;
    private javax.swing.JComboBox jCBIdentification;
    private javax.swing.JComboBox jCBcargo;
    private javax.swing.JComboBox jCBestado_civil;
    private com.toedter.calendar.JDateChooser jDCfecha_nacimiento;
    private javax.swing.JLabel jLIdentification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPForm;
    private javax.swing.JPanel jPFormControl;
    private javax.swing.JPanel jPId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFIdentification;
    private javax.swing.JTextField jTFapellidos;
    private javax.swing.JTextField jTFcedula;
    private javax.swing.JTextField jTFnombres;
    private javax.swing.JTextField jTFsalario;
    private javax.swing.JTextField jTFtelefono;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    private final ControlEmpleado controlEmpleado;
    private final Validador validador;
    private final LanzarMensaje lanzarMensaje;

    
}
