package GUI.GestionInformacion.Empleado;


import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Validadores.Validador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * JIFEmpleado 21/12/2015
 *
 * @author Álvaro Jose Lobatón Restrepo. Código: 1130054
 * @author Jhon Jairo Pantoja. Código: 1125572
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 * @author Alejandro Mejia Méndez. Código: 1330785
 */
public class JIFEmpleado extends AnclarVentanaInterna {

    /**
     * Creates new form JIFEmployee
     *
     * @param title Un string correspondiente al titulo del JInternalFrame
     * @param parent_w
     * @param parent_h
     */
    public JIFEmpleado(String title, int parent_w, int parent_h) {
        super();
        setTitle(title);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(900, 425);
        setLocation((int) (Math.abs(parent_w - getSize().width) / 2), (int) (Math.abs(parent_h - getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        // INICIALIZAMOS COMPONENTES
        initComponents();
        // INICIALIZAMOS ATRIBUTOS
        validador = new Validador();
        
        
        // CONTROL
        
        // Definimos el valor de la acción por defecto siempre en -1.
        
        // ACTUALIZAMOS EL COMBOBOX Y SETEAMOS SU ActionListener
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPId = new javax.swing.JPanel();
        jLIdentification = new javax.swing.JLabel();
        jTFIdentification = new javax.swing.JTextField();
        jCBIdentification = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPFormControl = new javax.swing.JPanel();
        jBNew = new javax.swing.JButton();
        jBRead = new javax.swing.JButton();
        jBUpdate = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLIdentification.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLIdentification.setText("Identificación: ");
        jPId.add(jLIdentification);

        jTFIdentification = new javax.swing.JTextField(20);
        jPId.add(jTFIdentification);

        jPId.add(jCBIdentification);

        jLabel10.setText("Cargo");

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 800));

        jPForm.setLayout(new java.awt.GridLayout(9, 2, 5, 5));

        jLabel3.setText("Cedula ");
        jPForm.add(jLabel3);
        jPForm.add(jTextField1);

        jLabel4.setText("Nombres");
        jPForm.add(jLabel4);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPForm.add(jTextField2);

        jLabel8.setText("Apellidos");
        jPForm.add(jLabel8);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPForm.add(jTextField3);

        jLabel9.setText("Fecha de nacimiento");
        jPForm.add(jLabel9);
        jPForm.add(jTextField4);

        jLabel2.setText("Estado civil");
        jPForm.add(jLabel2);
        jPForm.add(jTextField5);

        jLabel5.setText("Salario");
        jPForm.add(jLabel5);
        jPForm.add(jTextField7);

        jLabel6.setText("Cargo");
        jPForm.add(jLabel6);
        jPForm.add(jTextField8);

        getContentPane().add(jPForm, java.awt.BorderLayout.CENTER);

        jPFormControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBNew.setText("CREAR");
        jBNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNewActionPerformed(evt);
            }
        });
        jPFormControl.add(jBNew);

        jBRead.setText("BUSCAR");
        jBRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReadActionPerformed(evt);
            }
        });
        jPFormControl.add(jBRead);

        jBUpdate.setText("MODIFICAR");
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });
        jPFormControl.add(jBUpdate);

        jBDelete.setText("ELIMINAR");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });
        jPFormControl.add(jBDelete);

        getContentPane().add(jPFormControl, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestion de Empleados");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cleanGeneralDataForm.
     */
    
    /**
     * searchContract [Método encargado de buscar un contrato y colocar su
     * información en el formulario].
     *
     * @throws MyException
     */
    
    

    
    private void jBNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewActionPerformed
        
    }//GEN-LAST:event_jBNewActionPerformed

    private void jBReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReadActionPerformed
        
    }//GEN-LAST:event_jBReadActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // DEFINIMOS LA ACCIÓN A REALIZAR.
        
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed

        
    }//GEN-LAST:event_jBUpdateActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBNew;
    private javax.swing.JButton jBRead;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JComboBox jCBIdentification;
    private javax.swing.JLabel jLIdentification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPForm;
    private javax.swing.JPanel jPFormControl;
    private javax.swing.JPanel jPId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFIdentification;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
    
    private final Validador validador;
    

    
}
