package GUI.GestionInformacion.Tarjeta;

import Control.ControlEmpleado;
import Control.ControlEstacion;
import Control.ControlTarjeta;
import Control.ControlTurno;
import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Entidades.Empleado;
import Modelo.Entidades.Estacion;
import Modelo.Validadores.LanzarMensaje;
import Modelo.Excepciones.MiExcepcion;
import Modelo.Validadores.Validador;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.border.EtchedBorder;

/**
 *
 * JIFBuscarTarjeta
 * 
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 * 
 */

public class JIFBuscarTarjeta extends AnclarVentanaInterna {

    /**
     * Creates new form JIFViewProfile
     *
     * @param title
     * @param parentWidth
     * @param parentHeight
     * @throws Modelo.Excepciones.MiExcepcion
     */
    public JIFBuscarTarjeta(String title, int parentWidth, int parentHeight) throws MiExcepcion {
        super();
        this.parentWidth = parentWidth;
        this.parentHeight = parentHeight;
        setTitle(title);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(WIDTH_, HEIGHT_);
        setLocation((int) (Math.abs(this.parentWidth - this.getSize().width) / 2), (int) (Math.abs(this.parentHeight - this.getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        initComponents();
        initializeComponents();
        
        actualizarTarjetas();
        jCBIdTarjeta.addActionListener(manejadorEventos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPInformacion = new javax.swing.JPanel();
        jLCodigoEstacion = new javax.swing.JLabel();
        jTFIdTarjeta = new javax.swing.JTextField();
        jCBIdTarjeta = new javax.swing.JComboBox();
        jPLabels = new javax.swing.JPanel();
        jLControlPassword = new javax.swing.JLabel();
        jPControls = new javax.swing.JPanel();
        jPBotonBuscar = new javax.swing.JPanel();
        jPContenedorBoton = new javax.swing.JPanel();
        jBBuscarEstacion = new javax.swing.JButton();

        jPInformacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPInformacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPInformacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLCodigoEstacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCodigoEstacion.setText("Código de la Tarjeta: ");
        jPInformacion.add(jLCodigoEstacion);

        jTFIdTarjeta.setMaximumSize(new java.awt.Dimension(200, 25));
        jTFIdTarjeta.setMinimumSize(new java.awt.Dimension(40, 25));
        jTFIdTarjeta.setPreferredSize(new java.awt.Dimension(100, 25));
        jTFIdTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdTarjetaFocusLost(evt);
            }
        });
        jPInformacion.add(jTFIdTarjeta);

        jCBIdTarjeta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBIdTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPInformacion.add(jCBIdTarjeta);

        jPLabels.setLayout(new java.awt.GridLayout(3, 0));
        jPLabels.add(jLControlPassword);

        jPInformacion.add(jPLabels);

        jPControls.setLayout(new java.awt.GridLayout(3, 0));
        jPInformacion.add(jPControls);

        getContentPane().add(jPInformacion, java.awt.BorderLayout.NORTH);

        jPBotonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPBotonBuscar.setMaximumSize(new java.awt.Dimension(610, 37));
        jPBotonBuscar.add(jPContenedorBoton);

        jBBuscarEstacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBBuscarEstacion.setText("BUSCAR VENTA TARJETA");
        jBBuscarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarEstacionActionPerformed(evt);
            }
        });
        jPBotonBuscar.add(jBBuscarEstacion);

        getContentPane().add(jPBotonBuscar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarEstacionActionPerformed
        try {
            registros = false;
            displayTab();
        } catch (MiExcepcion ex) {
            Logger.getLogger(JIFBuscarTarjeta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBBuscarEstacionActionPerformed

    private void jTFIdTarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdTarjetaFocusLost
                    
            /*if(jTFCodigoEstacion.getText()!=""){
                
            String cod = jTFCodigoEstacion.getText();
            
            String codigo = "";
            
            String item = "";
            
            int indice = 0;
            
            boolean encontrado = false;
            
                for(int i=1; i<jCBCodigoEstacion.getItemCount(); i++){
                    
                    item = (String) jCBCodigoEstacion.getItemAt(i);
                    
                    for(int j=0; j<item.length(); j++) {
                        
                        if(item.charAt(i)==' ') { 
                                
                                codigo = item.substring(0, i);  
                                
                                if(cod.equals(codigo)) {
                                    indice = i;
                                    encontrado = true;
                                    break;
                                }
                                
                            }
                        
                    }
                    
                    if(encontrado){
                        break;
                    }
                }
                
            jCBCodigoEstacion.setSelectedIndex(indice);
                
            }else{
                jCBCodigoEstacion.setSelectedIndex(0);
            }*/
        
    }//GEN-LAST:event_jTFIdTarjetaFocusLost

    private void initializeComponents() {
        lanzarMensaje = new LanzarMensaje(this);
        manejadorEventos = new buscarEstacionManejadorEventos();
        controlTarjeta = new ControlTarjeta();
        controlEmpleado = new ControlEmpleado();
        validador = new Validador();
        registros = true;
    }

    private void actualizarTarjetas() throws MiExcepcion {
        Tarjeta[] tarjetas = controlTarjeta.listarTarjetas();
        if ((Arrays.asList(tarjetas)).isEmpty()) {
            
            if(!registros){
                dispose();
            }
            throw new MiExcepcion("No hay registro de ventas de tarjetas en la base de datos.");            
        }
        
        String[] codigos = new String[estaciones.length+1];
        
        codigos[0] = "Seleccione el código de la tarjeta...";
        
        for(int i=1; i<=tarjetas.length; i++){
            
            codigos[i] = tarjetas[i-1].getId() + " " + tarjetas[i-1].getNombre();
            
        }
        
        jCBIdTarjeta.setModel(new javax.swing.DefaultComboBoxModel(codigos));
    }
    
    private void actualizarListaEmpleados() throws MiExcepcion {
        Empleado[] empleados = controlEmpleado.listarEmpleadosCargo("AUXILIAR");
        if ((Arrays.asList(empleados)).isEmpty()) {
            throw new MiExcepcion("No hay auxiliares registrados en la base de datos.");
        }
        
        String[] cedulas = new String[empleados.length+1];
        
        cedulas[0] = "Seleccione la cédula del auxiliar...";
        
        for(int i=1; i<=empleados.length; i++){
            
            cedulas[i] = empleados[i-1].getCedula();
            
        }
        
        jCBCedulaVendedor.setModel(new javax.swing.DefaultComboBoxModel(cedulas));
    }

    
    private void displayTab() throws MiExcepcion {
        // Bloqueamos el boton Buscar
        jBBuscarEstacion.setEnabled(false);
        jTFIdTarjeta.setEditable(false);
        jCBIdTarjeta.setEnabled(false);
        // Desbloqueamos el Internal Frame     
        setLocked(false);
        // Definimos un nuevo tamaño.
        setSize(WIDTH_, 280);
        // Definimos el layot del panel...  
        jPUpdatePassword = new JPanel();
        jPUpdatePassword.setLayout(new BorderLayout());
        jPUpdatePassword.setBorder(new EtchedBorder());
        // Creamos un panel para las etiquetas.
        JPanel jPUpdateLabels = new JPanel();
        jPUpdateLabels.setLayout(new GridLayout(5, 1));
        // Creamos las etiquetas.
        JLabel jLCurrent = new JLabel("Cédula Vendedor:");
        JLabel jLNew = new JLabel("Saldo:");
        JLabel jLRetype = new JLabel("Fecha de la Venta:");
        JLabel jLHora = new JLabel("Hora de la Venta:");
        JLabel jLEstado = new JLabel("Estado de la Tarjeta:");
        // Añadimos las etiquetas.
        jPUpdateLabels.add(jLCurrent);
        jPUpdateLabels.add(jLNew);
        jPUpdateLabels.add(jLRetype);
        jPUpdateLabels.add(jLHora);
        jPUpdateLabels.add(jLEstado);
        // Creamos el panel para los campos de contraseña.
        JPanel jPUpdateTF = new JPanel();
        jPUpdateTF.setLayout(new GridLayout(5, 1));
        // Campos de contraseña.
        jCBCedulaVendedor = new JComboBox(); 
        jTFSaldo = new JTextField();
        jTFFecha = new JTextField();
        jTFHora = new JTextField();
        jCBEstado = new JComboBox();
        
        actualizarListaEmpleados();        
        
        // Añadimos los campos de texto al panel
        jPUpdateTF.add(jCBCedulaVendedor);
        jPUpdateTF.add(jTFSaldo);
        jPUpdateTF.add(jTFFecha);
        jPUpdateTF.add(jTFHora);
        jPUpdateTF.add(jCBEstado);        
        
        jPBotonesModificar = new JPanel();
        jPBotonesModificar.setLayout(new FlowLayout());
        //jPBotonesModificar.setBorder(new EtchedBorder());
        
        jBGuardarModificaciones = new JButton("GUARDAR MODIFICACIÓN");
        jBGuardarModificaciones.addActionListener(manejadorEventos);
        
        jBCancelar = new JButton("CANCELAR");
        jBCancelar.addActionListener(manejadorEventos);
        
        jPBotonesModificar.add(jBGuardarModificaciones);
        jPBotonesModificar.add(jBCancelar);
        
        jPBotonesModificar.setVisible(false);
        
        String codigo = jTFIdTarjeta.getText().trim();
        
        Tarjeta tarjeta = controlTarjeta.buscarTarjeta(codigo);
        
        jTFNombre.setText(estacion.getNombre());
        jTFDireccion.setText(estacion.getDireccion());
                
        for(int i=1; i<=jCBCedulaDirector.getItemCount(); i++) {
                        
            if(estacion.getCedulaDirector().equals(jCBCedulaDirector.getItemAt(i))) {
                jCBCedulaDirector.setSelectedIndex(i);
                break;
            }
            
        }
        
        jTFNombre.setEditable(false);
        jTFDireccion.setEditable(false);
        jCBCedulaDirector.setEnabled(false);
        
        // Creamos un panel para los botones
        JPanel jPUpdateButtons = new JPanel();
        //jPUpdateButtons.setLayout(new GridLayout(1, 2));
        jPUpdateButtons.setLayout(new FlowLayout());
        
        JPanel jPBotones = new JPanel();
        jPBotones.setLayout(new BoxLayout(jPBotones, BoxLayout.PAGE_AXIS));
        jPBotones.setBorder(new EtchedBorder());
        //jPBotones.setLayout(new FlowLayout());
        //jPBotones.setLayout(new GridLayout(1, 2));
        //jPUpdateButtons.setBorder(new EtchedBorder());
        // Creamos los botones.
        jBModificar = new JButton("MODIFICAR");
        jBModificar.addActionListener(manejadorEventos);
        
        jBEliminar = new JButton("ELIMINAR");
        jBEliminar.addActionListener(manejadorEventos);
        
        jBBuscar = new JButton("BUSCAR DE NUEVO");
        jBBuscar.addActionListener(manejadorEventos);
        
        // Procedemos a agregar los botones al panel
        jPUpdateButtons.add(jBModificar);
        jPUpdateButtons.add(jBEliminar);
        jPUpdateButtons.add(jBBuscar);
        
        jPBotones.add(jPBotonesModificar);
        jPBotones.add(jPUpdateButtons);
        // Procedemos a armar el panel completo.
        jPUpdatePassword.add(jPUpdateLabels, "Before");
        jPUpdatePassword.add(jPUpdateTF, "Center");
        jPUpdatePassword.add(jPBotones, "Last");
        
        //jPUpdatePassword.add(jPUpdateLabels, "Before");
        //jPUpdatePassword.add(jPUpdateTF);
        //jPUpdatePassword.add(jPBotonesModificar);
        
        //jPUpdatePassword.add(jPUpdateButtons, "Last");
        // Agregamos el panel ala ventana principal
        //this.add(jPUpdatePassword, "South");
        this.jPBotonBuscar.setLayout(new BoxLayout(jPBotonBuscar, BoxLayout.PAGE_AXIS));
        this.jPBotonBuscar.add(jPUpdatePassword);        
        // Bloqueamos de nuevo el internal frame.
        setLocked(true);
        // Actualizamos la interfaz.
        updateUI();
    }

    private void retractTab() {
        // Limpiamos los campos.
        this.jTFNombre.setText("");
        this.jTFDireccion.setText("");
        this.jCBCedulaDirector.setSelectedIndex(0);
        this.jTFIdTarjeta.setText("");
        this.jCBIdTarjeta.setSelectedIndex(0);
        // Debemos recoger la ventana y retirar los componentes.
        // Reactivamos el boton editar.
        jBBuscarEstacion.setEnabled(true);
        jTFIdTarjeta.setEditable(true);
        jCBIdTarjeta.setEnabled(true);
        // Retiramos los componentes:
        this.jPBotonBuscar.remove(jPUpdatePassword);
        jPBotonBuscar.setLayout(new FlowLayout());
        // Desbloqueamos el internal frame para devolverlo a su tamaño original.
        setLocked(false);
        setSize(WIDTH_, HEIGHT_);
        setLocked(true);
        // Actualizamos la interfaz grafica.
        updateUI();
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarEstacion;
    private javax.swing.JComboBox jCBIdTarjeta;
    private javax.swing.JLabel jLCodigoEstacion;
    private javax.swing.JLabel jLControlPassword;
    private javax.swing.JPanel jPBotonBuscar;
    private javax.swing.JPanel jPContenedorBoton;
    private javax.swing.JPanel jPControls;
    private javax.swing.JPanel jPInformacion;
    private javax.swing.JPanel jPLabels;
    private javax.swing.JTextField jTFIdTarjeta;
    // End of variables declaration//GEN-END:variables
    private final int parentWidth;
    private final int parentHeight;
    private JButton jBModificar;
    private JButton jBEliminar;
    private JButton jBBuscar;
    private JButton jBGuardarModificaciones;
    private JButton jBCancelar;
    private JTextField jTFSaldo;
    private JTextField jTFFecha;
    private JTextField jTFHora;
    private JComboBox jCBEstado;
    private JComboBox jCBCedulaVendedor;    
    private JPanel jPUpdatePassword;
    private JPanel jPBotonesModificar;
    private LanzarMensaje lanzarMensaje;
    private buscarEstacionManejadorEventos manejadorEventos;
    private final static int WIDTH_ = 650;
    private final static int HEIGHT_ = 120;
    private Validador validador;
    private ControlTarjeta controlTarjeta;
    private ControlEmpleado controlEmpleado;
    private boolean registros;
    
    private class buscarEstacionManejadorEventos implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            
            if(e.getSource() == jCBIdTarjeta) {
                
                try{
                    if(jCBIdTarjeta.getSelectedIndex()!=0){                                                                                          
                                
                        String informacion = (String) jCBIdTarjeta.getSelectedItem();
                        
                        String codigo = "";
                        
                        for(int i=0; i<informacion.length(); i++) {
                            
                            if(informacion.charAt(i)==' ') { 
                                
                                codigo = informacion.substring(0, i);  
                                
                                break;
                                
                            }
                        } 
                         
                        jTFIdTarjeta.setText(codigo);
                        
                    }else{
                        jTFIdTarjeta.setText("");
                    }
                    
                } catch (Exception ex){
                    jTFIdTarjeta.setText("");
                }          
            }
            
            if(e.getSource() == jBModificar){
                
                jPBotonesModificar.setVisible(true);
                jBModificar.setEnabled(false);
                jBEliminar.setEnabled(false);
                jBBuscar.setEnabled(false);
                
                jTFNombre.setEditable(true);
                jTFDireccion.setEditable(true);
                jCBCedulaDirector.setEnabled(true);
                
            }
            
            if(e.getSource() == jBGuardarModificaciones) {
                
                String[] informacion = new String[4];
                informacion[0] = jTFIdTarjeta.getText();
                informacion[1] = jTFNombre.getText().toUpperCase();
                informacion[2] = jTFDireccion.getText().toUpperCase();
                informacion[3] = (String) jCBCedulaDirector.getSelectedItem();
                
                try {
                                        
                    validador.validarCampoVacio(informacion[1], "NOMBRE");
                    validador.validarCampoVacio(informacion[2], "DIRECCIÓN");
                    
                    if(jCBCedulaDirector.getSelectedItem()==jCBCedulaDirector.getItemAt(0)) {

                        lanzarMensaje.mostrarMessageDialog("Debe seleccionar la cédula del director.", title, JOptionPane.INFORMATION_MESSAGE); 

                    } else {

                    Estacion[] estacion = controlEstacion.yaEsDirector(informacion[3]);

                    if ((Arrays.asList(estacion)).isEmpty()) {

                        controlEstacion.modificarEstacion(informacion);
                        lanzarMensaje.mostrarMessageDialog("La estación ha sido modificada en la base de datos con éxito.", title, JOptionPane.INFORMATION_MESSAGE);
                        actualizarEstaciones();
                        retractTab();
                    }else {

                        lanzarMensaje.mostrarMessageDialog("No se pudo modificar la estación, ya que el empleado con la cédula " + informacion[3] 
                                + " ya es director de la estación " + estacion[0].getNombre(), 
                                title, JOptionPane.ERROR_MESSAGE);              

                    }
                    }                   
                    
                } catch (MiExcepcion ex) {
                    lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
                }               
                
            }
            
            if(e.getSource() == jBCancelar || e.getSource() == jBBuscar) {
                
                retractTab();
                
            }
            
            if(e.getSource() == jBEliminar) {
                
                String codigo = jTFIdTarjeta.getText();
                
                try {
                    controlEstacion.eliminarEstacion(codigo);
                    lanzarMensaje.mostrarMessageDialog("La estación fue eliminada con éxito.", title, JOptionPane.INFORMATION_MESSAGE);
                    actualizarEstaciones();                    
                } catch (MiExcepcion ex) {
                    
                    lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
                    
                } finally {
                    
                    retractTab();
                    
                }
                
            }
            
        }
    }
    
};
