package GUI.GestionInformacion.Tarjeta;

import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Validadores.LanzarMensaje;
import Modelo.Excepciones.MiExcepcion;
import Modelo.Validadores.Validador;
import Modelo.Entidades.Empleado;
import Control.ControlEstacion;
import Control.ControlEmpleado;
import Control.ControlTarjeta;
import Modelo.Entidades.Estacion;
import Modelo.Entidades.Tarjeta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * JIFCrearTarjeta
 * 
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 * 
 */

public class JIFCrearTarjeta extends AnclarVentanaInterna {

    /**
     * Creates new form JIFEmployee
     *
     * @param titulo Un string correspondiente al titulo del JInternalFrame
     * @param parent_w
     * @param parent_h
     */
    public JIFCrearTarjeta(String titulo, int parent_w, int parent_h) throws MiExcepcion {
        super();
        this.parentWidth = parent_w;
        this.parentHeight = parent_h;
        setTitle(titulo);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(WIDTH_, HEIGHT_);
        setLocation((int) (Math.abs(this.parentWidth - this.getSize().width) / 2), (int) (Math.abs(this.parentHeight - this.getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        // INICIALIZAMOS COMPONENTES
        initComponents();
        // INICIALIZAMOS ATRIBUTOS
        validador = new Validador();
        lanzarMensaje = new LanzarMensaje(this);
        
        controlTarjeta = new ControlTarjeta();
        controlEmpleado = new ControlEmpleado();
        // CONTROL
        /*setEnabledGeneralDataForm(false);
        setEnabledContractForm(false);
        setEnabledSaveControl(false);*/
        // Definimos el valor de la acción por defecto siempre en -1.
        //action = -1;
        // ACTUALIZAMOS EL COMBOBOX Y SETEAMOS SU ActionListener
        actualizarListaEmpleados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotonCrear = new javax.swing.JPanel();
        jBCrearTarjeta = new javax.swing.JButton();
        jPInformacionEstacion = new javax.swing.JPanel();
        jLCodigoEstacion = new javax.swing.JLabel();
        jTFCodigoTarjeta = new javax.swing.JTextField();
        jLCedulaDirector = new javax.swing.JLabel();
        jCBCedulaEmpleado = new javax.swing.JComboBox();
        jLCedulaDirector1 = new javax.swing.JLabel();
        jTFSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 800));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPBotonCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCrearTarjeta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBCrearTarjeta.setText("VENDER TARJETA");
        jBCrearTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearTarjetaActionPerformed(evt);
            }
        });
        jPBotonCrear.add(jBCrearTarjeta);

        getContentPane().add(jPBotonCrear, java.awt.BorderLayout.PAGE_END);

        jPInformacionEstacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPInformacionEstacion.setLayout(new java.awt.GridLayout(3, 2, 0, 10));

        jLCodigoEstacion.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLCodigoEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigoEstacion.setText("Código de la Tarjeta:");
        jPInformacionEstacion.add(jLCodigoEstacion);
        jPInformacionEstacion.add(jTFCodigoTarjeta);

        jLCedulaDirector.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLCedulaDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCedulaDirector.setText("Cédula Vendedor:");
        jPInformacionEstacion.add(jLCedulaDirector);

        jCBCedulaEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPInformacionEstacion.add(jCBCedulaEmpleado);

        jLCedulaDirector1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLCedulaDirector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCedulaDirector1.setText("Saldo:");
        jPInformacionEstacion.add(jLCedulaDirector1);

        jTFSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSaldoActionPerformed(evt);
            }
        });
        jPInformacionEstacion.add(jTFSaldo);

        getContentPane().add(jPInformacionEstacion, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cleanGeneralDataForm.
     */
    private void limpiarCampos() {
                
        jTFCodigoTarjeta.setText("");
        jTFSaldo.setText("");
        jCBCedulaEmpleado.setSelectedIndex(0);
        
    }
    
    /**
     * setEnabledGeneralDataForm
     *
     * @param bool
     */
    private void setEnabledGeneralDataForm(boolean bool) {
        jTFCodigoTarjeta.setEnabled(bool);
        jCBCedulaEmpleado.setEnabled(bool);
        
    }

    private void setEnabledContractForm(boolean bool) {
        
    }

    private void setEnabledRelateForm(boolean bool) {
        
    }

    private void setEditableGeneralDataForm(boolean bool) {
        jTFCodigoTarjeta.setEditable(bool);
        jCBCedulaEmpleado.setEditable(bool);
        
    }

    private void setEditableContractForm(boolean bool) {
        
    }

    private void setEditableRelateForm(boolean bool) {
        
    }

    private void setEnabledSaveControl(boolean bool) {
        
    }

    private void setEnabledFormControl(boolean bool) {
        jBCrearTarjeta.setEnabled(bool);
       
    }
        
    private void actualizarListaEmpleados() throws MiExcepcion {
        Empleado[] empleados = controlEmpleado.listarEmpleadosCargo("AUXILIAR");
        if ((Arrays.asList(empleados)).isEmpty()) {
            throw new MiExcepcion("No hay auxiliares registrados en la base de datos.");
        }
        
        String[] cedulas = new String[empleados.length+1];
        
        cedulas[0] = "Seleccione la cédula del auxiliar...";
        
        for(int i=1; i<=empleados.length; i++){
            
            cedulas[i] = empleados[i-1].getCedula();
            
        }
        
        jCBCedulaEmpleado.setModel(new javax.swing.DefaultComboBoxModel(cedulas));
    }

    

    /**
     * searchEmployee [Método encargado de buscar la informacion general del
     * empleado y ponerla en el formulario].
     *
     * @throws MyException
     * @throws ParseException
     */
    

    private void jBCrearTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearTarjetaActionPerformed
        
        String[] informacion = new String[3];
        
        informacion[0] = jTFCodigoTarjeta.getText().trim();
        informacion[1] = jTFSaldo.getText();
        informacion[2] = (String) jCBCedulaEmpleado.getSelectedItem();
                      
        try {                           
            
            validador.validarCampoVacio(informacion[0], "El CÓDIGO DE LA TARJETA");
            validador.validarCadenaNumeros(informacion[0], "El CÓDIGO DE LA TARJETA ");
            validador.validarCampoVacio(informacion[1], "El SALDO");                                
            
            validador.validarDouble(informacion[1], "SALDO");
            
            if(jCBCedulaEmpleado.getSelectedItem()==jCBCedulaEmpleado.getItemAt(0)) {
                
                lanzarMensaje.mostrarMessageDialog("Debe seleccionar la cédula del empleado.", title, JOptionPane.INFORMATION_MESSAGE); 
                
            } else {
            
            Tarjeta[] tarjeta = controlTarjeta.yaExisteVenta(informacion[0]);
            
            if ((Arrays.asList(tarjeta)).isEmpty()) {
                
                controlTarjeta.crearTarjeta(informacion);

                lanzarMensaje.mostrarMessageDialog("La venta de la tarjeta fue realizada con éxito.", title, JOptionPane.INFORMATION_MESSAGE); 

                limpiarCampos();
                
            }else {
                                   
                lanzarMensaje.mostrarMessageDialog("La tarjeta con el código " + informacion[0] 
                        + " ya fue vendida.", 
                        title, JOptionPane.ERROR_MESSAGE);               
                            
            }
            }
            
        } catch (MiExcepcion ex) {
            
            lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jBCrearTarjetaActionPerformed

    private void jTFSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSaldoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearTarjeta;
    private javax.swing.JComboBox jCBCedulaEmpleado;
    private javax.swing.JLabel jLCedulaDirector;
    private javax.swing.JLabel jLCedulaDirector1;
    private javax.swing.JLabel jLCodigoEstacion;
    private javax.swing.JPanel jPBotonCrear;
    private javax.swing.JPanel jPInformacionEstacion;
    private javax.swing.JTextField jTFCodigoTarjeta;
    private javax.swing.JTextField jTFSaldo;
    // End of variables declaration//GEN-END:variables
    private final static int WIDTH_ = 470;
    private final static int HEIGHT_ = 220;
    private final int parentWidth;
    private final int parentHeight;
    private final LanzarMensaje lanzarMensaje;
    private final Validador validador;
    private final ControlTarjeta controlTarjeta;  
    private final ControlEmpleado controlEmpleado;
    
};    
