package GUI.GestionInformacion.Bus;

import Control.ControlBus;
import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Validadores.LanzarMensaje;
import Modelo.Excepciones.MiExcepcion;
import Modelo.Validadores.Validador;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * JIFCrearBus
 * 
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 * 
 */

public class JIFCrearBus extends AnclarVentanaInterna {

    /**
     * Creates new form JIFEmployee
     *
     * @param titulo Un string correspondiente al titulo del JInternalFrame
     * @param parent_w
     * @param parent_h
     */
    public JIFCrearBus(String titulo, int parent_w, int parent_h) throws MiExcepcion {
        super();
        this.parentWidth = parent_w;
        this.parentHeight = parent_h;
        setTitle(titulo);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(WIDTH_, HEIGHT_);
        setLocation((int) (Math.abs(this.parentWidth - this.getSize().width) / 2), (int) (Math.abs(this.parentHeight - this.getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        // INICIALIZAMOS COMPONENTES
        initComponents();
        // INICIALIZAMOS ATRIBUTOS
        validador = new Validador();
        lanzarMensaje = new LanzarMensaje(this);
        controlBus = new ControlBus();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotonCrear = new javax.swing.JPanel();
        jBCrearBus = new javax.swing.JButton();
        jPInformacionBus = new javax.swing.JPanel();
        jLPlaca = new javax.swing.JLabel();
        jTFPlacaBus = new javax.swing.JTextField();
        jLModeloBus = new javax.swing.JLabel();
        jTFModeloBus = new javax.swing.JTextField();
        jLMarcaBus = new javax.swing.JLabel();
        jTFMarcaBus = new javax.swing.JTextField();
        jLCapacidad = new javax.swing.JLabel();
        jTFCapacidad = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 800));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPBotonCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCrearBus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBCrearBus.setText("CREAR BUS");
        jBCrearBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearBusActionPerformed(evt);
            }
        });
        jPBotonCrear.add(jBCrearBus);

        getContentPane().add(jPBotonCrear, java.awt.BorderLayout.PAGE_END);

        jPInformacionBus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPInformacionBus.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLPlaca.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPlaca.setText("Placa:");
        jPInformacionBus.add(jLPlaca);
        jPInformacionBus.add(jTFPlacaBus);

        jLModeloBus.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLModeloBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLModeloBus.setText("Modelo:");
        jPInformacionBus.add(jLModeloBus);

        jTFModeloBus = new javax.swing.JTextField(20);
        jPInformacionBus.add(jTFModeloBus);

        jLMarcaBus.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLMarcaBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMarcaBus.setText("Marca:");
        jPInformacionBus.add(jLMarcaBus);
        jPInformacionBus.add(jTFMarcaBus);

        jLCapacidad.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCapacidad.setText("Capacidad:");
        jPInformacionBus.add(jLCapacidad);
        jPInformacionBus.add(jTFCapacidad);

        jLTipo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo.setText("Tipo:");
        jPInformacionBus.add(jLTipo);

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el tipo de bus...", "ARTICULADO", "PADRON", "ALIMENTADOR" }));
        jPInformacionBus.add(jCBTipo);

        getContentPane().add(jPInformacionBus, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cleanGeneralDataForm.
     */
    private void limpiarCampos() {
                
        jTFPlacaBus.setText("");
        jTFModeloBus.setText("");
        jTFMarcaBus.setText("");
        jTFCapacidad.setText("");
        jCBTipo.setSelectedIndex(0);
        
    }  
   
    private void jBCrearBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearBusActionPerformed
        
        String[] informacion = new String[5];
        
        informacion[0] = jTFPlacaBus.getText().trim();
        informacion[1] = jTFModeloBus.getText().trim();
        informacion[2] = jTFMarcaBus.getText().trim().toUpperCase();
        informacion[3] = jTFCapacidad.getText().trim();
        informacion[4] = (String) jCBTipo.getSelectedItem();
                      
        try {                           
            
            validador.validarCampoVacio(informacion[0], "PLACA");  
            validador.validarCadenaNumeros(informacion[1], "El MODELO del bus ");
            validador.validarLongitudCadena(informacion[1], "El MODELO", 4);                       
            validador.validarCadenaNumeros(informacion[3], "La CAPACIDAD del bus ");
            
            if("".equals(informacion[3])) {
                    informacion[3] = "0";            
            }
            
            if (jCBTipo.getSelectedItem()==jCBTipo.getItemAt(0)) {
                
                lanzarMensaje.mostrarMessageDialog("Debe seleccionar el tipo de bus.", title, JOptionPane.INFORMATION_MESSAGE);                 
                
            }else {
                
                controlBus.crearBus(informacion);
                
                lanzarMensaje.mostrarMessageDialog("El bus fue guardado con éxito.", title, JOptionPane.INFORMATION_MESSAGE);  

                limpiarCampos();                        
                            
            }
            
        } catch (MiExcepcion ex) {
            
            lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jBCrearBusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearBus;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLCapacidad;
    private javax.swing.JLabel jLMarcaBus;
    private javax.swing.JLabel jLModeloBus;
    private javax.swing.JLabel jLPlaca;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JPanel jPBotonCrear;
    private javax.swing.JPanel jPInformacionBus;
    private javax.swing.JTextField jTFCapacidad;
    private javax.swing.JTextField jTFMarcaBus;
    private javax.swing.JTextField jTFModeloBus;
    private javax.swing.JTextField jTFPlacaBus;
    // End of variables declaration//GEN-END:variables
    private final static int WIDTH_ = 470;
    private final static int HEIGHT_ = 260;
    private final int parentWidth;
    private final int parentHeight;
    private final LanzarMensaje lanzarMensaje;
    private final Validador validador;
    private final ControlBus controlBus;       

}
