package GUI.GestionInformacion.Turno;

import GUI.PaquetePrincipal.AnclarVentanaInterna;
import Modelo.Validadores.LanzarMensaje;
import Modelo.Excepciones.MiExcepcion;
import Modelo.Validadores.Validador;
import Modelo.Entidades.Empleado;
import Control.ControlEstacion;
import Control.ControlEmpleado;
import Control.ControlTurno;
import Modelo.Entidades.Turno;
import java.text.ParseException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * JIFCrearTurno
 * 
 * @author Mauricio Bernardo Dominguez Bocanegra. Código: 9927680
 * @author Martha Cecilia Holguin Tovar. Código: 1129455
 * @author Jesús Alberto Ramírez Otálvaro. Código: 1422554
 * 
 */

public class JIFCrearTurno extends AnclarVentanaInterna {

    /**
     * Creates new form JIFEmployee
     *
     * @param titulo Un string correspondiente al titulo del JInternalFrame
     * @param parent_w
     * @param parent_h
     */
    public JIFCrearTurno(String titulo, int parent_w, int parent_h) throws MiExcepcion {
        super();
        this.parentWidth = parent_w;
        this.parentHeight = parent_h;
        setTitle(titulo);
        setResizable(false);
        setClosable(true);
        setMaximizable(false);
        setSize(WIDTH_, HEIGHT_);
        setLocation((int) (Math.abs(this.parentWidth - this.getSize().width) / 2), (int) (Math.abs(this.parentHeight - this.getSize().height) / 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocked(true);
        // INICIALIZAMOS COMPONENTES
        initComponents();
        // INICIALIZAMOS ATRIBUTOS
        validador = new Validador();
        lanzarMensaje = new LanzarMensaje(this);
        controlTurno = new ControlTurno();
        
        // CONTROL
        /*setEnabledGeneralDataForm(false);
        setEnabledContractForm(false);
        setEnabledSaveControl(false);*/
        // Definimos el valor de la acción por defecto siempre en -1.
        //action = -1;
        // ACTUALIZAMOS EL COMBOBOX Y SETEAMOS SU ActionListener
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotonCrear = new javax.swing.JPanel();
        jBCrearEstacion = new javax.swing.JButton();
        jPInformacionEstacion = new javax.swing.JPanel();
        jLCodigoEstacion = new javax.swing.JLabel();
        jTFCodigoTurno = new javax.swing.JTextField();
        jLNombreEstacion = new javax.swing.JLabel();
        jTFHoraInicio = new javax.swing.JTextField();
        jLDireccionEstacion = new javax.swing.JLabel();
        jTFHoraFinalizacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(407, 800));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPBotonCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCrearEstacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBCrearEstacion.setText("CREAR TURNO");
        jBCrearEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearEstacionActionPerformed(evt);
            }
        });
        jPBotonCrear.add(jBCrearEstacion);

        getContentPane().add(jPBotonCrear, java.awt.BorderLayout.PAGE_END);

        jPInformacionEstacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPInformacionEstacion.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLCodigoEstacion.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLCodigoEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigoEstacion.setText("Codigo del Turno :");
        jPInformacionEstacion.add(jLCodigoEstacion);
        jPInformacionEstacion.add(jTFCodigoTurno);

        jLNombreEstacion.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLNombreEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombreEstacion.setText("Hora de inicio:");
        jPInformacionEstacion.add(jLNombreEstacion);

        jTFHoraInicio = new javax.swing.JTextField(20);
        jPInformacionEstacion.add(jTFHoraInicio);

        jLDireccionEstacion.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLDireccionEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDireccionEstacion.setText("Hora de finalizacion :");
        jPInformacionEstacion.add(jLDireccionEstacion);
        jPInformacionEstacion.add(jTFHoraFinalizacion);

        getContentPane().add(jPInformacionEstacion, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cleanGeneralDataForm.
     */
    private void limpiarCampos() {
                
        jTFCodigoTurno.setText("");
        jTFHoraInicio.setText("");
        jTFHoraFinalizacion.setText("");
               
    }
    
    /**
     * setEnabledGeneralDataForm
     *
     * @param bool
     */
    private void setEnabledGeneralDataForm(boolean bool) {
        jTFCodigoTurno.setEnabled(bool);
        jTFHoraFinalizacion.setEnabled(bool);
       
        
    }

    private void setEnabledContractForm(boolean bool) {
        
    }

    private void setEnabledRelateForm(boolean bool) {
        
    }

    private void setEditableGeneralDataForm(boolean bool) {
        jTFCodigoTurno.setEditable(bool);
        jTFHoraFinalizacion.setEditable(bool);
       
        
    }

    private void setEditableContractForm(boolean bool) {
        
    }

    private void setEditableRelateForm(boolean bool) {
        
    }

    private void setEnabledSaveControl(boolean bool) {
        
    }

    private void setEnabledFormControl(boolean bool) {
        jBCrearEstacion.setEnabled(bool);
       
    }
        
    

    


    

    private void jBCrearEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearEstacionActionPerformed
        
        String[] informacion = new String[4];
        
        informacion[0] = jTFCodigoTurno.getText().trim();
        informacion[1] = jTFHoraInicio.getText().trim().toUpperCase();
        informacion[2] = jTFHoraFinalizacion.getText().trim().toUpperCase();
        
                      
        try {                           
            
            validador.validarCampoVacio(informacion[0], "CÓDIGO");
            validador.validarCampoVacio(informacion[1], "FECHA INICIO");
            validador.validarCampoVacio(informacion[2], "FECHA FINALIZACION");
                        
            validador.validarCadenaNumeros(informacion[0], "El CÓDIGO DE LA ESTACIÓN ");
            
            
            
            
            
            Turno[] turno  = controlTurno.yaExisteTurno(informacion[0]);
            
            if ((Arrays.asList(turno)).isEmpty()) {
                
                controlTurno.crearTurno(informacion);

                lanzarMensaje.mostrarMessageDialog(" El turno fue creado con éxito.", title, JOptionPane.INFORMATION_MESSAGE); 

                limpiarCampos();
                
            }else {
                                   
                lanzarMensaje.mostrarMessageDialog("No se pudo crear el turno , ya que el turno con el codigo " + informacion[0] 
                        + " ya existe ", title, JOptionPane.ERROR_MESSAGE);               
                            
            }
            
            
        } catch (MiExcepcion ex) {
            
            lanzarMensaje.mostrarMessageDialog(ex.getMessage(), title, JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jBCrearEstacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearEstacion;
    private javax.swing.JLabel jLCodigoEstacion;
    private javax.swing.JLabel jLDireccionEstacion;
    private javax.swing.JLabel jLNombreEstacion;
    private javax.swing.JPanel jPBotonCrear;
    private javax.swing.JPanel jPInformacionEstacion;
    private javax.swing.JTextField jTFCodigoTurno;
    private javax.swing.JTextField jTFHoraFinalizacion;
    private javax.swing.JTextField jTFHoraInicio;
    // End of variables declaration//GEN-END:variables
    private final static int WIDTH_ = 470;
    private final static int HEIGHT_ = 220;
    private final int parentWidth;
    private final int parentHeight;
    private final LanzarMensaje lanzarMensaje;
    private final Validador validador;     
    private final ControlTurno controlTurno;
    
    
    
}
